{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-haproxy
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
  annotations:
    {{- with .Values.haproxy.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
    {{- $serviceType := .Values.haproxy.service.type }}
    {{- range .Values.haproxy.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
      {{- if and (eq $serviceType "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
{{- end }}
